public class DemoHandleException {
    public static void main(String[] args) {
//        try {
//            double result = 10/2;
//            System.out.println(result);
//        }
//        catch (Exception e){
//            System.out.println(e.getMessage());
//        }
//        Xử lý nhiều exception
//        try {
//            double result = 10/0;
//            System.out.println(result);
//            String text = null;
//            System.out.println(text.length());
//        }
//        catch (ArithmeticException e){
//            System.out.println(e.getMessage());
//        }
//        catch (NullPointerException ex){
//            System.out.println(ex.getMessage());
//        }
////        Finally : Được chạy kể cả có lỗi
//        try {
//            double result = 10/0;
//            System.out.println(result);
//        }
//        catch (Exception e){
//            System.out.println(e.getMessage());
//        }
//        finally {
//            System.out.println("Code continue");
//        }


    }
}
